export const LOAD_ACCOUNT_LIST = 'LOAD_ACCOUNT_LIST';
export const LOAD_ACCOUNT_SUCCESS = 'LOAD_ACCOUNT_SUCCESS';

export const SEARCH_HISTORY = 'SEARCH_HISTORY';
export const SEARCH_NEW_ORDERS = 'SEARCH_NEW_ORDERS';
