export const LOAD_ACCOUNT_SUCCESS = 'LOAD_ACCOUNT_SUCCESS';
export const LOAD_ACCOUNT_ERROR = 'LOAD_ACCOUNT_ERROR';
export const ACCOUNT_CHANGE = 'ACCOUNT_CHANGE';

export const SHOW_OLD_ORDERLINES = 'SHOW_OLD_ORDERLINES';
export const SHOW_NEW_ORDERLINES = 'SHOW_NEW_ORDERLINES';

export const GET_ORDER_STATUS = 'GET_ORDER_STATUS';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_ERROR = 'GET_ORDER_HISTORY_ERROR';

export const PREDICT_ORDER_STATUS = 'PREDICT_ORDER_STATUS';
export const PREDICT_ORDER_SUCCESS = 'PREDICT_ORDER_SUCCESS';
export const PREDICT_ORDER_ERROR = 'PREDICT_ORDER_ERROR';

export const UPDATE_SINGLE_ORDER_SUCCESS = 'UPDATE_SINGLE_ORDER_SUCCESS';
export const UPDATE_SINGLE_ORDER_ERROR = 'UPDATE_SINGLE_ORDER_ERROR';
export const UPDATE_SINGLE_ORDER_STATUS = 'UPDATE_SINGLE_ORDER_STATUS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'